[package]
name = "rust_transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler_builtins = "0.1.101"
wasm-bindgen = "0.2"
